### ISSUE TITLE
Match pattern not working with Windows path style

### ISSUE THREAD

**Issue by tintin92350** [SchwarzIT/spectral-intellij-plugin#102]
**Describe the bug**
When using Windows path style in the `Included path patterns` field as below, it doesn't find the file.

Path : `api-specifications\openapi\spec-v1.yaml`

**To Reproduce**

1. Open spectral settings
2. Enter the following path : `api-specifications\openapi\spec-v1.yaml` or any path to existing specification but with backslash
3. Close your specification file and re-open it
4. Spectral doesn't lint the file

**Expected behavior**
It should take backslash as normal slash in Windows context and find the two paths in the same way:
```
api-specifications/openapi/spec-v1.yaml
api-specifications\openapi\spec-v1.yaml
```

**Environment:**
 - Plugin version: 2.1.3
 - OS: Windows 10

**Comment by markbrockhoff** [comment]
Hi @tintin92350 thanks for the report. I'll close this issue as it's related to #89. Please feel free to follow the progress on improved Windows support there.
