### ISSUE TITLE
Error "Invalid ruleset provided" occurs with every ruleset provided

### ISSUE THREAD

**Issue by kkeck-nordlb** [SchwarzIT/spectral-intellij-plugin#12]
Please see issue reported here: https://github.com/SchwarzIT/api-linter-rules/issues/22
(Sorry for the duplicate.)

**Comment by markbrockhoff** [comment]
No problem, I'll just close it here and we work with this issue: https://github.com/SchwarzIT/api-linter-rules/issues/22
