### ISSUE TITLE
How can I debug the plugin?

### ISSUE THREAD

**Issue by anikitin** [SchwarzIT/spectral-intellij-plugin#16]
There are some strange issues, some my OpenAPI files are not properly handled  by Spectral plugin, problems view is stuck and is not updated if I make changes... I cannot find the pattern. Swagger-cli and idea OpenAPI plugin handle this file properly. 

How can I see logs of Spectral plugin or debug output to nail down the issues?

**Comment by markbrockhoff** [comment]
Hi @anikitin sorry for the late reply.
I just opened a PR for v1.0.7 of the plugin that includes detailed logging. You can follow the description in the readme on how to look at the logs once it's released.
