### ISSUE TITLE
The linter messages do not refresh after text change

### ISSUE THREAD

**Issue by karelhusa** [SchwarzIT/spectral-intellij-plugin#21]
When I have linting issue and make a fix in the source OpenAPI text, the highlighting and linter message remains.

The refresh time is very different, sometimes it happens in e.g. 20 seconds, other times I close the window, open it again and the linting still is not resfreshed.

My laptop has no performance issues. 

Plugin version: 1.0.7

**Comment by markbrockhoff** [comment]
Hi, thanks for your report, sorry for the delayed answer. We just released a new major version of the plugin. I'm closing this issue as it should be resolved with the new version.
Please feel free to try it out. It now features an indicator to show while linting is ongoing. 
Please note, that we decided to no longer bundle the Spectral CLI within the plugin, so you'll have to install it on your system yourself.
