### ISSUE TITLE
spectral detected the php composer.json package file as openAPI documentation file

### ISSUE THREAD

**Issue by vikbert** [SchwarzIT/spectral-intellij-plugin#4]
Plugin detected the complete content in **composer.json** as **invalid openAPI documentation** in PhpStorm IDE.
After I disabled the spectral plugin, then IDE will not detect the composer.json as invalid. see screenshot.

**Invalid detection:**
<img width="1904" alt="Screenshot 2022-02-05 at 16 23 10" src="https://user-images.githubusercontent.com/3229226/152647999-da7c0cf2-7c4c-4026-9b7c-3dee80a74f30.png">

**after disable plugin**
<img width="1904" alt="Screenshot 2022-02-05 at 16 29 56" src="https://user-images.githubusercontent.com/3229226/152648078-6cd7aa32-334a-4ba3-a487-fcbf75d924f9.png">

should it possible, if plugins should have whitelist or blacklist and should detect the openAPI file only?

**Comment by markbrockhoff** [comment]
As stated in our README, the plugin lints every json file by default. However you can change this behaviour by specifying a glob pattern to select only the files you want to be linted in the settings.
![image](https://user-images.githubusercontent.com/95471369/152751557-4907af66-6da6-4726-bad0-0414e9457b99.png)
If you put for example "**openapi.json" into the field "Included files" only files ending with "openapi.json" will be linted.
