### ISSUE TITLE
Update version of embedded spectral

### ISSUE THREAD

**Issue by yspotts** [SchwarzIT/spectral-intellij-plugin#44]
The version of the embedded spectral is `6.2.1`. 

The latest version of spectral is `6.6.0`.

Unfortunately, the older version contains backward compatibility issues, most significantly around how `aliases` are defined. (see https://github.com/stoplightio/spectral/pull/2085 and https://github.com/stoplightio/spectral/pull/2033)

The latest [spectral URL style guide](https://apistylebook.stoplight.io/docs/url-guidelines) makes use of aliases; without the latest version of spectral, this style guide cannot be used as is.

**Comment by markbrockhoff** [comment]
Hi, thanks for the report and sorry for the delayed response.
We wanted to make the setup of the plugin as easy as possible by bundling the CLI with it. But we also noticed the downsides of this approach and decided to no longer bundle it with our latest version 2.0.0.
From now on the spectral cli installed on your system will be used for linting. This should fix most of the problems the plugin hat till now.
Please feel free to upgrade and try it out with the latest version of the spectral CLI.
