### ISSUE TITLE
Plugin is not taking the system env variables by default

### ISSUE THREAD

**Issue by samyu614** [SchwarzIT/spectral-intellij-plugin#53]
I am dealing with an usecase where I need to set an environment variable to run spectral in my corporate environment
But the plugin doesn't apply the env variables set in my system to the process that runs spectral.
It would be great if the plugin have this feature.

**Comment by noelos** [comment]
In the same position. I need to $ref in definitions from internally-hosted schemas. This is easy enough with spectral command-line as I can just do the following before running spectral:
export NODE_EXTRA_CA_CERTS=/path/to/corporate-root-ca.pem

But as there's no way to pass in environment variables, this doesn't work for the plugin.

**Comment by markbrockhoff** [comment]
Hi, thanks for your report, sorry for the delayed answer. 
Until now the spectral CLI was bundled with the plugin, we did this to make the setup as easy as possible.
However, we also noticed that this approach has some downsides and decided to release a new major version of the plugin that no longer bundles the spectral cli.
As v2 uses the spectral executable within your systems path, you should be able to set environement variables globally and  they should be respected. Please feel free to try it out using v2.
I'd close this issue as it should be solved by v2 but feel free to re-open it in case it isnt.

**Comment by noelos** [comment]
I like the approach of using a system-installed instance of spectral, but how does the plugin detect it? For clarity, I'm using a Mac and so the idea of a "system's path" or "setting environment variables globally" doesn't make a lot of sense. Is there an expectation this would work for Windows only?

**Comment by markbrockhoff** [comment]
Hi @noelos, there surely is no intention for the plugin to be windows only.
The executable is detected by simply executing the "spectral" command on the CLI. So as long as it's installed in a directory that's listed in your Systems $PATH variable it should be detected. If you installed spectral in a default way e.g. Homebrew or npm this should just work out of the box.
About setting env vars globally: As the CLI is executed in a default Terminal it will pickup all globally set env vars. So you can just export the env var inside your .zshrc and it should be picked up by spectral. If you just want it to be set for spectral, you can even create an alias for the spectral command to set the env var before executing the actual spectral command.

In general you could say: If you can run `spectral lint ...` inside your terminal and it works, the Plugin should work as well.
