### ISSUE TITLE
Yaml support ?

### ISSUE THREAD

**Issue by bastien-phi** [SchwarzIT/spectral-intellij-plugin#6]
It looks like this plugin does not support linting yaml files...  Am I wrong ?

It would be great to have this !

**Comment by sn0wbi** [comment]
Hi @bastien-phi we´re working on this at the moment and we will push a new version to the Jetbrains marketplace soon. We leave this isse in open state until the new version is available.

**Comment by sn0wbi** [comment]
Hi @bastien-phi we finished dev for yaml support [Pull Request](https://github.com/SchwarzIT/spectral-intellij-plugin/pull/8#pullrequestreview-881541822). Will be published automatically to Jetbrains Marketplace after merge.

**Comment by markbrockhoff** [comment]
Version 1.0.2 is currently reviewed by JetBrains. It should appear in the Marketplace in 1 or 2 days. After the update you can change the linted files in the plugins settings to .yml / .yaml files and lint those as well. For more information on how to change these settings see: https://github.com/SchwarzIT/spectral-intellij-plugin#customizable-file-matching-pattern
